### ISSUE TITLE
CSS output when adding site

### ISSUE THREAD

**Issue by willmot** [joehoyle/vienna#29]
Trying to add `http://www.tõm.com` causes a page with CSS code to be displayed. The app must be force quit to get rid of it. The site isn't successfully added.

**Comment by willmot** [comment]
![img_4043](https://cloud.githubusercontent.com/assets/308507/16666202/88082b76-447e-11e6-9224-9d2451eea778.PNG)

**Comment by joehoyle** [comment]
@willmot do you get the step of signing into your WordPress site and Authorizing the application?

If so, can you create me a subscriber user and send me the username  / password so I can test.

Thanks

**Comment by willmot** [comment]
> @willmot do you get the step of signing into your WordPress site and Authorizing the application?

I don't it shows up as soon as I enter the domain and click "Add Site":
![ezgif-4217280091](https://cloud.githubusercontent.com/assets/308507/18004860/8232461e-6b8e-11e6-8fed-67776f0320e9.gif)

I added you a subscriber level user 👍
