### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by nickrobinson352** [joehoyle/vienna#32]
![image](https://cloud.githubusercontent.com/assets/11671613/21281195/d64cdb56-c3b8-11e6-8cec-7065c239d264.png)

I keep getting this error. I follows the 3 steps and went back to xcode but still get the same exception. What am I missing ?

**Comment by joehoyle** [comment]
I think this can be closed out now as a lot has changed since this issue was created. Re-open if you have problems with the latest code though.
